FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY nginx.production.global.conf /etc/nginx/nginx.conf
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
COPY index.html styles.css app.js /usr/share/nginx/html/
